# Development/Local values for MSPR Serverless
# Override the default values for local development

# Use local OpenFaaS gateway (if running OpenFaaS locally)
openfaas:
  gatewayInternal: "http://localhost:8080"

# Frontend configuration for development
frontend:
  image:
    repository: cofrap-frontend
    tag: dev
    pullPolicy: Never  # Use local images
  replicaCount: 1
  
  # Disable ingress for local development
  ingress:
    enabled: false
  
  # Use NodePort for local access
  service:
    type: NodePort
    port: 80
    targetPort: 3000
    nodePort: 30080

# PostgreSQL configuration for development
postgresql:
  persistence:
    storageClass: ""  # Use default storage class
    size: 1Gi  # Smaller size for development
  
  auth:
    password: "devpassword"

# Disable production features for development
adminer:
  enabled: true

# Keep migrations enabled
migrations:
  enabled: true
