apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: monitoring
  labels:
    release: prometheus
    app: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
