apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-certificate
  namespace: cofrap
spec:
  secretName: frontend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - cofrap.germainleignel.com
