apiVersion: v1
kind: Service
metadata:
  name: openfaas-metrics
  namespace: openfaas-fn
  labels:
    app: openfaas-metrics
    release: prometheus
spec:
  selector:
    app: openfaas-function
  ports:
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openfaas-functions-monitor
  namespace: monitoring
  labels:
    release: prometheus
    app: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: openfaas-metrics
  namespaceSelector:
    matchNames:
      - openfaas-fn
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
