version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
  namespace: cofrap

functions:
  generate-password:
    lang: python3
    handler: ./handler
    image: registry.germainleignel.com/library/generate-password:latest
    environment:
      write_debug: "true"
      read_debug: "true"
      combine_output: "false"
    environment_file:
      - .env
    secrets:
      - db-credentials
    annotations:
      topic: "password-generation"
    labels:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "10"
      com.openfaas.scale.factor: "20"
