{{- if .Values.migrations.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-migrations
  namespace: {{ .Values.namespace }}
data:
  {{- range .Values.migrations.migrations }}
  {{ .name }}: |-
{{ .content | indent 4 }}
  {{- end }}
{{- end }}
