{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: {{ .Values.namespace }}
  labels:
    app: db-migration
spec:
  template:
    spec:
      restartPolicy: {{ .Values.migrations.restartPolicy }}
      containers:
      - name: migrate
        image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
        imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
        command: 
          - /bin/sh
          - -c
          - |
            # Wait for PostgreSQL to be ready
            until pg_isready -h postgres -U postgres; do
              echo "Waiting for PostgreSQL..."
              sleep 1
            done
            
            # Create the database if it doesn't exist
            PGPASSWORD=password psql -h postgres -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'cofrap'" | grep -q 1 || \
            PGPASSWORD=password createdb -h postgres -U postgres cofrap
            
            # Run migrations
            for f in /migrations/*.up.sql; do
              echo "Running migration: $f"
              PGPASSWORD=password psql -h postgres -U postgres -d cofrap -f "$f"
            done
        volumeMounts:
          - name: migrations
            mountPath: /migrations
            readOnly: true
        env:
          - name: PGPASSWORD
            value: password
      volumes:
        - name: migrations
          configMap:
            name: db-migrations
  backoffLimit: {{ .Values.migrations.backoffLimit }}
{{- end }}
