{{- if .Values.frontend.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-certificate
  namespace: {{ .Values.namespace }}
spec:
  secretName: frontend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.frontend.ingress.hosts }}
  - {{ .host | quote }}
  {{- end }}
{{- end }}
