{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
          name: http
        env:
        - name: NODE_ENV
          value: production
        - name: OPENFAAS_GATEWAY_INTERNAL
          value: {{ .Values.openfaas.gatewayInternal | quote }}
        - name: PORT
          value: "{{ .Values.frontend.containerPort }}"
        - name: HOST
          value: "0.0.0.0"
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        {{- if .Values.frontend.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.frontend.livenessProbe.path }}
            port: http
          initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.frontend.livenessProbe.timeoutSeconds }}
        {{- end }}
{{- end }}
